version: '3'

services:
  dockerperf:
    image: dockerperf
    build:
      context: ./DockerPerf
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
