version: '3'

services:
  dockerperffx:
    environment:
      - DEV_ENVIRONMENT=1
    ports:
      - "80"
    volumes:
      - ./DockerPerfFx:C:\inetpub\wwwroot
networks:
  default:
    external:
      name: nat
