version: '3'

services:
  mycompany.visitors.web:
    environment:
      - DEV_ENVIRONMENT=1
    volumes:
      - ./Visitors/MyCompany.Visitors.Web:C:\inetpub\wwwroot
      
  mycompany.visitors.crmsvc:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./Visitors/MyCompany.Visitors.CRMSvc:C:\app
      - ${USERPROFILE}\.nuget\packages\:C:\.nuget\packages:ro
    entrypoint:
        cmd /c "dotnet.exe --additionalProbingPath c:\\.nuget\\packages bin/Debug/netcoreapp1.1/MyCompany.Visitors.CRMSvc.dll"
        
networks:
  default:
    external:
      name: nat